version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
    environment:
      - WEB_SERVER_HTTP_PORT=${WEB_SERVER_HTTP_PORT}
      - WEB_SERVER_HTTPS_PORT=${WEB_SERVER_HTTPS_PORT}
    networks:
      - backend
      - frontend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www
      - ./nginx/logs:/var/log/nginx
    ports:
      - ${WEB_SERVER_HTTP_PORT}:80
      - ${WEB_SERVER_HTTPS_PORT}:443

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - PHP_FPM_EXT_APCU=${PHP_FPM_EXT_APCU}
        - PHP_FPM_XDEBUG=${PHP_FPM_XDEBUG}
    volumes:
      - ../workdir:/var/www
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
